### ISSUE TITLE
Typecast check neccessary?

### ISSUE THREAD

**Issue by ayacoo** [WapplerSystems/typo3-guestbook#1]
https://github.com/WapplerSystems/typo3-guestbook/blob/release/v10/Classes/Controller/GuestbookController.php#L81

At tt-address we fell into the trap last time:
https://github.com/FriendsOfTYPO3/tt_address/commit/2e56d658fd9d0d125a0acbe1e837de104df7e6b3

**Comment by svewap** [comment]
Thank you for the hint. Done ;-)
