### ISSUE TITLE
mandatory E-Mail is not checked

### ISSUE THREAD

**Issue by jacques2017** [WapplerSystems/typo3-guestbook#6]
Hi,
when I set E-Mail as mandatory, there is no * in the frontend and if I doesn't fill out the E-Mail in the form, there is no Error.
I use Version 11.01 on TYPO3 V11.5.22

Cheers,
Jacques

**Comment by jacques2017** [comment]
I've found the bug in https://github.com/WapplerSystems/typo3-guestbook/tree/release/v11/Classes/Form/Factory/GuestbookFormFactory.php

![grafik](https://user-images.githubusercontent.com/26480486/219740797-825b985a-e69c-41a4-967a-73b3a73dbac5.png)

**Comment by svewap** [comment]
fixed this in version 11.0.2
